### PR TITLE
Changes to make it compatible with expo

### PR DESCRIPTION
**Pull request by truca**
Expo uses the maps package differently (it exports the MapView package from the expo package), and when you try to use this package, you get an error because you're creating components twice (one from expo, one from you using react-native-maps), so i changed the dependencies that you used. **I recommend creating a branch for this**

### CODE REVIEW

**Review by donedgardo — CHANGES_REQUESTED** [review]
This would break if they don't have expo. maybe add conditional imports.

**Comment by raphaelbadia** [comment]
It would be cool to add this in an 'expo' branch and write about it in the readme

**Comment by chernandez7** [comment]
Expo 34 allows for this to work with out any modifications.

**Comment by 39otrebla** [comment]
Guys, I know this is sooo old but I wanted to let you know that we are planning a major redesign of the library using HoC approach rather than component composition. This would allow importing MapView from whatever package app-side and just pass it as parameter of the HoC.

Please follow #115 for updates on this matter.

**Comment by 39otrebla** [comment]
#115

**Pull request closed without merging**
