### PR TITLE
Replacing uses of react deprecated methods

### PR DESCRIPTION
**Pull request by adteulade**
Replacing componentWillUpdate() and componentWillReceiveProps() by componentDidUpdate().

### CODE REVIEW

**Comment by adteulade** [comment]
Hey guys, first thanks for that package here is a PR to remove uses of react deprecated methods componentWillUpdate() and componentWillReceiveProps().

I tested it with our app here at Pod Point and it seems to do the trick let me know what you think :-)

**Comment by lcastillo-evc** [comment]
Can we get this merged soon? Thanks!

**Comment by ramonvermeulen** [comment]
@novalabio can we get this merged with a new release please?

**Comment by 39otrebla** [comment]
Please see #112 .

**Pull request closed without merging**
