### PR TITLE
remove deprecated lifecycle methods

### PR DESCRIPTION
**Pull request by r0b0t3d**
Remove `componentWillUpdate` and `componentWillReceivedProps`

### CODE REVIEW

**Comment by 39otrebla** [comment]
@r0b0t3d unfortunately, `componentWillReceiveProps` cannot be simply replaced by `componentDidUpdate`. I believe we need a deeper refactoring.

**Comment by 39otrebla** [comment]
Also, I see changes not related to removing deprecated lifecycle methods. Please open different PR for each improvement.

**Comment by r0b0t3d** [comment]
@39otrebla It seems the implementation of `componentWillUpdate` just to check if the cluster's size changed then configuring the animation if possible.
So I think we could handle animation when the data is updated (inside `clusterize` and `onRegionChangeComplete`). It is necessary when removing deprecated lifecycle method `componentWillUpdate `.

Inside docs https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops.

> If you need to perform a side effect (for example, data fetching or an animation) in response to a change in props, use `componentDidUpdate` lifecycle instead.

Could you consider to look at this PR again?
Thanks,

**Comment by 39otrebla** [comment]
@r0b0t3d the point is that `LayoutAnimation.configureNext()` automatically configures animation for the `next` render cycle, i.e. calling it in `componentDidUpdate` would have no effect (unless we force state update, which is not an option though).

I believe we have two options (but I still have to go through a proper analysis):

- stick with `LayoutAnimation` and migrate to `getSnapshotBeforeUpdate`, which is called before every re-render. In this case, we should add some logic to prevent unnecessary calls to `LayoutAnimation.configureNext()` as it should be called IIF clusters or data are changed.
- migrate to manual animations, using `Animated` library, so that we can call it in `componentDidUpdate` (still, after having checked that data or clusters are changed).

**Pull request closed without merging**
