### PR TITLE
Added multi points at the same address support.

### PR DESCRIPTION
**Pull request by Ble3k**
Hi! First of all, I want to thank you for this work, it's very helpful.

This PR is aimed to make available multi-points with the same lng/lat support. In my case, for example, it was necessary to make an array of such points to be visible as one marker, not cluster.

### CODE REVIEW

**Comment by ccoeder** [comment]
Hi @Ble3k ,

Is this pr separates the markers on the same lat, lon as in the picture below?

Thank you.

screen shot 2018-07-15 at 22 59 12

**Comment by Ble3k** [comment]
This PR doesn't separate. This PR unite 2 (for example) points with the same lat/lng in one marker with any view, that u need.

**Comment by ccoeder** [comment]
Ok, got it! Hope it merged soon.

**Comment by YazeedAsaad** [comment]
@ccoeder did you find any solution to separate the points at the same address ?

**Pull request closed without merging**
