### PR TITLE
textStyle and containerStyle aren't required anymore

### PR DESCRIPTION
**Pull request by brunovianarezende**
this is specially useful when a custom renderCluster is used

### CODE REVIEW

**Comment by 39otrebla** [comment]
Going to keep `textStyle` and `containerStyle` for backward compatibility for a 'bit, with proper deprecation notice. See [this commit](https://github.com/novalabio/react-native-maps-super-cluster/commit/ee4007cc7b4d506fd40ff114bb87684b76870b2a).

**Comment by brunovianarezende** [comment]
The commit doesn't remove textStyle and containerStyle, it just makes the properties optional...

**Comment by 39otrebla** [comment]
Indeed:

> Going to keep textStyle and containerStyle for backward compatibility for a 'bit, with proper deprecation notice.

**Comment by brunovianarezende** [comment]
sorry, I meant: My Pull Request doesn't remove textStyle and containerStyle, it just makes them optional...
in other words, with my patch, if I use renderCluster, I'm not required to provide textStyle nor containerStyle anymore.

**Comment by 39otrebla** [comment]
I see. Good catch, haven't removed the "required" flag from PropTypes.

**Comment by 39otrebla** [comment]
Merged, updated github release and re-published npm package with minor version bump (from 1.3.0 to 1.3.1).
Thanks!

**Comment by brunovianarezende** [comment]
You're welcome :)

**Pull request merged**
